const SUPABASE_URL = "https://kvwsqfnyebyjncfgvqnd.supabase.co";
const SUPABASE_KEY = "sb_publishable_CssKC6R2Nqtl3McbvR3f4A_jNJtz3hg";
function json(data,status=200,headers={}) { return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}}); }
async function body(req){ try{return await req.json()}catch{return {}} }
function bearer(req){const h=req.headers.get("authorization")||"";return h.startsWith("Bearer ")?h.slice(7):null}
async function supabaseUser(req){ const token=bearer(req); if(!token)return null; const r=await fetch(SUPABASE_URL+"/auth/v1/user",{headers:{apikey:SUPABASE_KEY,authorization:`Bearer ${token}`}}); if(!r.ok)return null; return await r.json(); }
async function requireUser(req){const u=await supabaseUser(req);if(!u)throw Object.assign(new Error("Não autenticado"),{status:401});return u}
async function rest(req,path,options={}){ const token=bearer(req); const headers={apikey:SUPABASE_KEY,"content-type":"application/json","accept-profile":"nexora","content-profile":"nexora",...(token?{authorization:`Bearer ${token}`}:{ } ),...(options.headers||{})}; return fetch(SUPABASE_URL+"/rest/v1/"+path,{...options,headers}); }
async function createProfile(req){ const u=await requireUser(req), b=await body(req); const r=await rest(req,"profiles",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({id:u.id,full_name:String(b.full_name||u.user_metadata?.full_name||""),role:"student",status:"active"})}); const data=await r.json().catch(()=>({})); if(!r.ok)return json({error:data.message||"Falha ao criar perfil"},r.status); return json({profile:Array.isArray(data)?data[0]:data}); }
async function me(req){ const u=await requireUser(req); const r=await rest(req,`profiles?id=eq.${encodeURIComponent(u.id)}&select=id,full_name,role,status`); const data=await r.json(); return json({user:u,profile:data[0]||null}); }
async function courses(req){ await requireUser(req); const r=await rest(req,"courses?select=id,slug,title,description,status,minimum_score,position&order=position.asc"); const data=await r.json(); return json({courses:data}); }
async function progress(req){ const u=await requireUser(req), b=await body(req); const payload={user_id:u.id,lesson_id:b.lesson_id,progress:Math.max(0,Math.min(100,Number(b.progress??100))),updated_at:new Date().toISOString(),completed_at:Number(b.progress??100)>=100?new Date().toISOString():null}; const r=await rest(req,"lesson_progress?on_conflict=user_id,lesson_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(payload)}); const data=await r.json().catch(()=>({})); if(!r.ok)return json({error:data.message||"Falha ao salvar progresso"},r.status);return json({ok:true,data}); }
async function router(req,env){ const url=new URL(req.url); if(url.pathname==="/api/health")return json({ok:true,service:"nexora-academy-supabase",database:"supabase",time:new Date().toISOString()}); if(url.pathname==="/api/nexora/profile"&&req.method==="POST")return createProfile(req); if(url.pathname==="/api/nexora/me")return me(req); if(url.pathname==="/api/nexora/courses")return courses(req); if(url.pathname==="/api/nexora/progress"&&req.method==="POST")return progress(req); return env.ASSETS.fetch(req); }
export default {async fetch(req,env,ctx){try{return await router(req,env)}catch(e){return json({error:e.message||"Erro interno"},e.status||500)}}};