begin;
-- Fase 6 — passe de profundidade após auditoria do módulo 2
update nexora.lessons
 set content=((content - (jsonb_array_length(content)-1)) || $json$[{"type":"guided_practice","title":"Separe configuração de estado em uma regra real","body":"Cenário: uma entrega cobra R$ 20 de frete quando o pedido fica abaixo de R$ 200. O valor do pedido muda para cada cliente, mas o limite de R$ 200 e o frete padrão de R$ 20 pertencem à política atual.\n\nModele os três valores. Depois imagine que a empresa alterou o limite para R$ 250. Quantos pontos da solução você gostaria de modificar? Se a resposta for vários, existe um sinal de que a regra está espalhada demais."},{"type":"professional_context","title":"Constantes também ajudam testes e configuração","body":"Em aplicações maiores, limites e taxas podem vir de configuração, banco ou ambiente, mas o princípio permanece: o restante do código deve tratá-los como valores nomeados da regra. Isso facilita testar cenários diferentes e evita que números iguais, porém semanticamente distintos, sejam confundidos."}]$json$::jsonb || jsonb_build_array(content->(jsonb_array_length(content)-1)))
 where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=2 limit 1) and position=2;
update nexora.lessons
 set content=((content - (jsonb_array_length(content)-1)) || $json$[{"type":"example","title":"Faixas exigem mais de uma fronteira","body":"Considere a classificação: nota abaixo de 5 = reprovado; de 5 até menos de 7 = recuperação; 7 ou mais = aprovado.\n\nAgora existem duas fronteiras importantes: 5 e 7. Casos como 4,9; 5; 6,9; 7 ajudam a provar que as faixas não possuem buracos nem sobreposição. A mesma técnica vale para preços, idades, estoque e níveis de serviço."},{"type":"guided_practice","title":"Construa uma tabela de fronteira","body":"Escolha uma regra com limite — idade mínima, estoque baixo ou valor para desconto. Monte três colunas: entrada, resultado esperado e justificativa. Inclua pelo menos um valor abaixo, o limite e um acima.\n\nDepois altere propositalmente `>=` para `>` ou `<=` para `<` e identifique qual linha da tabela passa a falhar. Assim você transforma o teste em prova da regra."},{"type":"professional_context","title":"Erros de fronteira aparecem em regras críticas","body":"Faixas de comissão, elegibilidade de crédito, SLA, idade mínima, limite de estoque e descontos são exemplos em que um único símbolo pode afetar clientes reais. Por isso equipes maduras escrevem casos de fronteira como parte da especificação, não apenas depois que um bug aparece."}]$json$::jsonb || jsonb_build_array(content->(jsonb_array_length(content)-1)))
 where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=2 limit 1) and position=5;
commit;
