begin;
-- Fase 6 — LC Content Standard 1.0: refactor pedagógico do módulo 3 — Decisões
update nexora.modules
set description=$txt$Construa decisões verificáveis com condições, ramos, faixas, tabelas de decisão e tratamento explícito de entradas inválidas.$txt$
where id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1);
update nexora.lessons
set objective=$txt$Transformar uma regra verbal simples em uma condição booleana, identificando claramente pergunta, dados necessários, fronteira e resultado esperado antes de escolher um caminho.$txt$,
    estimated_minutes=28,
    content=$json$[{"type":"story","title":"Antes do caminho existe uma pergunta","body":"Um sistema não começa uma decisão pelo que deve fazer. Primeiro ele precisa responder uma pergunta. “O pedido tem valor suficiente para frete grátis?” “A idade atende ao mínimo?” “O estoque chegou ao ponto de reposição?”\n\nA condição é essa pergunta traduzida para uma expressão que produz verdadeiro ou falso."},{"type":"concept","title":"Condição é uma pergunta verificável sobre o estado","body":"Se `valorPedido >= 200`, a expressão não executa o frete nem mostra uma mensagem. Ela apenas responde se a regra foi satisfeita.\n\nSeparar a pergunta da ação ajuda a testar a lógica antes de construir os ramos. Você deve conseguir dizer quais valores tornam a condição verdadeira e quais a tornam falsa."},{"type":"purpose","title":"Decidir bem começa por escrever a pergunta certa","body":"Muitos bugs de decisão surgem porque a condição mistura regra e efeito. Quando a pergunta fica explícita, você pode validar dados, fronteiras e significado sem se distrair com a ação que virá depois."},{"type":"example","title":"Frete grátis a partir de R$ 200","body":"Requisito: pedidos de R$ 200 ou mais não pagam frete.\n\nPergunta: o valor do pedido atingiu o limite?\nCondição: `valorPedido >= LIMITE_FRETE`.\n\nCasos de prova: 199 → falso; 200 → verdadeiro; 201 → verdadeiro."},{"type":"guided_analysis","title":"Isole a pergunta antes de escolher a resposta","body":"Pegue uma regra como “bloquear login após 3 tentativas inválidas”. Escreva apenas a condição que pergunta se o limite foi atingido. Depois liste um caso falso, o caso da fronteira e um caso verdadeiro.\n\nNão escreva ainda o que o sistema deve fazer. O objetivo é provar a pergunta."},{"type":"mistake","title":"Não esconda a condição dentro da ação","body":"Frases como “se for maior, mostrar aprovado” misturam o critério e a consequência. Primeiro defina `atingiuNotaMinima = nota >= 7`; depois use esse booleano na decisão. A regra fica mais legível e testável."},{"type":"recap","items":["Condição é uma pergunta que produz booleano.","A fronteira pertence à condição, não à ação.","Casos abaixo, no limite e acima ajudam a provar a pergunta.","Nomear uma condição pode tornar a decisão mais clara."]}]$json$::jsonb,
    lab_type='expression',
    lab_config=$json${"checkpoint":{"question":"A regra diz 'frete grátis em pedidos de R$ 200 ou mais'. Qual condição representa a pergunta corretamente?","options":["valorPedido > 200","valorPedido >= 200","valorPedido < 200","valorPedido == 0"],"answer":1,"feedback":"Correto. A condição inclui a própria fronteira de R$ 200.","feedback_incorrect":"A expressão precisa retornar verdadeiro também quando o pedido vale exatamente R$ 200."},"expression":{"title":"Condition Lab — prove a pergunta","scenario":"O sistema deve considerar atingido o limite quando o cliente fizer 3 ou mais tentativas inválidas.","instruction":"Escolha a condição e confira o comportamento em torno da fronteira.","options":["tentativas > 3","tentativas >= 3","tentativas < 3","tentativas == 0"],"answer":1,"cases":[{"input":"2 tentativas","expected":"falso"},{"input":"3 tentativas","expected":"verdadeiro"},{"input":"4 tentativas","expected":"verdadeiro"}],"feedback":"Condição correta. A fronteira de 3 tentativas está incluída.","feedback_incorrect":"Teste exatamente 3 tentativas: a regra já deve ser verdadeira nesse ponto."},"module":"Decisões","editorial_version":"lc-content-standard-1.0","pedagogy":"regra-ramos-casos-validacao"}$json$::jsonb
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=1;
update nexora.lessons
set objective=$txt$Construir uma decisão de dois caminhos com SE e SENÃO, garantindo que os ramos sejam mutuamente compreensíveis e que toda entrada válida produza uma saída definida.$txt$,
    estimated_minutes=30,
    content=$json$[{"type":"story","title":"Uma pergunta pode dividir o fluxo em dois caminhos","body":"Depois de saber se uma condição é verdadeira ou falsa, o sistema precisa decidir o que fazer em cada caso. Em frete, por exemplo: se o pedido atingiu o limite, frete zero; senão, frete padrão.\n\nSE e SENÃO tornam essa bifurcação explícita."},{"type":"concept","title":"SE trata o caminho verdadeiro; SENÃO cobre o restante","body":"O bloco SE executa quando a condição é verdadeira. O SENÃO não significa erro; ele representa todos os casos válidos que não satisfizeram a condição.\n\nEm uma decisão binária bem definida, qualquer entrada válida deve cair em exatamente um dos dois ramos."},{"type":"example","title":"Uma regra completa de frete","body":"`SE valorPedido >= 200 ENTÃO`\n`    frete = 0`\n`SENÃO`\n`    frete = 20`\n`FIM`\n\nPara 250, só o primeiro ramo executa. Para 150, só o segundo. O fluxo nunca deve executar os dois."},{"type":"comparison","title":"Dois IFs independentes não são automaticamente um SE/SENÃO","items":["Dois IFs podem executar os dois blocos se as condições se sobrepuserem.","SE/SENÃO comunica que os caminhos são excludentes.","Quando as alternativas são complementares, SENÃO reduz repetição da condição.","Se o caso falso não possui ação, o SENÃO pode ser desnecessário."]},{"type":"guided_practice","title":"Faça teste de mesa nos dois ramos","body":"Use dois valores: um que satisfaça a condição e outro que não satisfaça. Para cada um, marque qual linha do pseudocódigo executa e qual saída é produzida.\n\nSe algum caso não produz saída ou produz duas saídas incompatíveis, a decisão precisa ser revisada."},{"type":"professional_context","title":"Bifurcações aparecem em validações, preços e permissões","body":"Sistemas usam decisões binárias para liberar/bloquear, aplicar/não aplicar, mostrar/ocultar e aceitar/recusar. A clareza dos dois caminhos facilita testes e revisão de regra."},{"type":"recap","items":["SE executa o caminho verdadeiro.","SENÃO cobre os casos restantes daquela decisão.","Ramos complementares devem ser mutuamente exclusivos.","Teste pelo menos um caso de cada caminho."]}]$json$::jsonb,
    lab_type='pseudocode',
    lab_config=$json${"checkpoint":{"question":"Em uma decisão SE/SENÃO, o que o SENÃO representa?","options":["Sempre um erro.","Os casos que não satisfizeram a condição do SE.","Uma segunda condição obrigatoriamente.","Um laço de repetição."],"answer":1,"feedback":"Correto. SENÃO cobre o caminho restante da decisão.","feedback_incorrect":"SENÃO é o ramo executado quando a condição do SE é falsa."},"module":"Decisões","editorial_version":"lc-content-standard-1.0","pedagogy":"regra-ramos-casos-validacao"}$json$::jsonb
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=2;
update nexora.lessons
set objective=$txt$Modelar decisões com três ou mais faixas usando SENÃO SE, organizando condições em ordem segura e provando que as faixas não deixam lacunas nem criam resultados conflitantes.$txt$,
    estimated_minutes=34,
    content=$json$[{"type":"purpose","title":"Quando duas respostas não bastam, surge o problema das faixas","body":"Notas, níveis de risco, preços, idade e prioridade costumam ter mais de duas classificações. Nesses casos, uma cadeia SENÃO SE permite testar possibilidades em sequência até encontrar a primeira condição verdadeira."},{"type":"concept","title":"A ordem das condições altera o resultado","body":"Em uma cadeia SENÃO SE, a primeira condição verdadeira encerra a busca. Por isso uma condição ampla colocada cedo demais pode impedir que uma condição mais específica seja alcançada.\n\nSe `nota >= 5` vier antes de `nota >= 7`, uma nota 9 será classificada no primeiro ramo e nunca chegará ao ramo de aprovação."},{"type":"example","title":"Classificação por nota sem sobreposição lógica","body":"Uma abordagem segura é testar do maior limite para o menor:\n\n`SE nota >= 7 → Aprovado`\n`SENÃO SE nota >= 5 → Recuperação`\n`SENÃO → Reprovado`\n\nPara 8: aprovado. Para 6: recuperação. Para 4: reprovado."},{"type":"guided_analysis","title":"Converta a cadeia em intervalos","body":"Leia cada ramo como um intervalo real. Aprovado: [7, +∞). Recuperação: [5, 7). Reprovado: abaixo de 5.\n\nEssa representação ajuda a perceber lacunas e sobreposições. Teste 4,9; 5; 6,9; 7 e 10."},{"type":"mechanics","title":"Checklist para uma cadeia de faixas","items":["Identifique todas as fronteiras.","Decida se cada limite é inclusivo ou exclusivo.","Ordene condições para que ramos específicos não fiquem inacessíveis.","Use SENÃO para o restante quando o domínio já foi validado.","Monte casos exatamente nas fronteiras."]},{"type":"mistake","title":"Condições corretas na ordem errada continuam produzindo classificação errada","body":"`SE nota >= 5` é uma condição válida isoladamente. O problema aparece quando ela vem antes de `SE nota >= 7` e intercepta casos que deveriam receber outra classificação. A decisão deve ser avaliada como sistema, não como linhas isoladas."},{"type":"mastery","title":"Você domina faixas quando consegue provar a cobertura","items":["Todo valor válido cai em algum ramo.","Um valor não recebe duas classificações incompatíveis.","As fronteiras produzem o resultado especificado.","A ordem das condições é justificável."]},{"type":"recap","items":["SENÃO SE permite múltiplos caminhos.","A primeira condição verdadeira vence.","Faixas devem cobrir o domínio sem ambiguidades.","Tabelas de casos ajudam a provar ordem e fronteiras."]}]$json$::jsonb,
    lab_type='decision_table',
    lab_config=$json${"checkpoint":{"question":"Para classificar nota >=7 como Aprovado e nota >=5 como Recuperação, qual ordem é mais segura?","options":["Testar >=5 antes de >=7.","Testar >=7 antes de >=5.","Testar apenas ==7.","A ordem nunca altera o resultado."],"answer":1,"feedback":"Correto. A condição mais exigente deve ser avaliada antes da faixa mais ampla.","feedback_incorrect":"A primeira condição verdadeira encerra a cadeia; uma condição ampla cedo demais pode capturar notas maiores."},"decision_table":{"title":"Decision Table — faixas de nota","scenario":"Classifique cada nota: 7 ou mais = Aprovado; de 5 até menos de 7 = Recuperação; abaixo de 5 = Reprovado.","outcomes":["Aprovado","Recuperação","Reprovado"],"rows":[{"case":"nota = 4,9","answer":2,"hint":"Logo abaixo da primeira fronteira."},{"case":"nota = 5","answer":1,"hint":"Exatamente na fronteira de recuperação."},{"case":"nota = 6,9","answer":1,"hint":"Ainda abaixo de 7."},{"case":"nota = 7","answer":0,"hint":"Exatamente na fronteira de aprovação."},{"case":"nota = 9","answer":0,"hint":"Acima da maior fronteira."}],"feedback":"Tabela consistente. As faixas cobrem os limites sem lacunas.","feedback_incorrect":"Revise as fronteiras 5 e 7 e lembre que o próprio limite pertence à faixa indicada."},"module":"Decisões","editorial_version":"lc-content-standard-1.0","pedagogy":"regra-ramos-casos-validacao"}$json$::jsonb
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=3;
update nexora.lessons
set objective=$txt$Combinar condições com operadores lógicos sem perder a regra de negócio, usando agrupamento explícito e casos que isolem cada condição para detectar permissões ou recusas indevidas.$txt$,
    estimated_minutes=32,
    content=$json$[{"type":"story","title":"Uma decisão pode depender de várias perguntas ao mesmo tempo","body":"Para liberar um benefício, talvez seja necessário que o cliente esteja ativo E tenha pelo menos 6 meses de cadastro. Para prioridade, pode bastar ser idoso OU gestante. A decisão final nasce da combinação de perguntas booleanas."},{"type":"concept","title":"Condição composta continua sendo uma única pergunta","body":"`clienteAtivo && mesesCadastro >= 6` combina dois booleanos e produz um resultado final. O sistema não precisa tratar isso como duas decisões separadas se a regra exige simultaneidade."},{"type":"comparison","title":"E, OU e agrupamentos mudam a população aprovada","items":["E restringe: todas as condições precisam ser verdadeiras.","OU amplia: pelo menos uma condição verdadeira é suficiente.","Parênteses definem quais condições formam um grupo.","Uma condição intermediária nomeada pode tornar a regra mais fácil de auditar."]},{"type":"example","title":"Perfil elegível e conta ativa","body":"Regra: cliente deve estar ativo E (ser VIP OU ter compra acima de R$ 1.000).\n\nUma leitura clara é `temPerfil = vip || compraAlta`; depois `elegivel = clienteAtivo && temPerfil`."},{"type":"guided_practice","title":"Isole cada condição com casos mínimos","body":"Crie casos em que apenas uma parte muda: ativo+VIP; inativo+VIP; ativo+não VIP com compra baixa; ativo+compra alta. Essa matriz mostra se E e OU foram usados no lugar correto."},{"type":"mistake","title":"Expressão que funciona em um caso pode estar permissiva demais","body":"Se você testa apenas ativo+VIP, tanto E quanto várias combinações erradas podem retornar verdadeiro. Testes que isolam cada condição são necessários para distinguir regras parecidas."},{"type":"professional_context","title":"Autorização é um exemplo em que lógica composta precisa ser precisa","body":"Permissões costumam combinar identidade, papel, status, propriedade do recurso e contexto. Um OU indevido pode ampliar acesso. Por isso regras compostas merecem testes negativos, não apenas casos autorizados."},{"type":"recap","items":["Condições compostas produzem um booleano final.","E restringe e OU representa alternativas.","Agrupamento precisa refletir o requisito.","Teste cenários que isolem cada condição."]}]$json$::jsonb,
    lab_type='expression',
    lab_config=$json${"checkpoint":{"question":"Regra: cliente ativo E (VIP OU compra >= 1000). Qual estrutura representa melhor a intenção?","options":["clienteAtivo || vip || compraAlta","clienteAtivo && (vip || compraAlta)","clienteAtivo && vip && compraAlta","!clienteAtivo && (vip || compraAlta)"],"answer":1,"feedback":"Correto. O status ativo é obrigatório; VIP e compra alta são alternativas dentro do grupo.","feedback_incorrect":"Separe a exigência obrigatória das duas alternativas de perfil."},"expression":{"title":"Expression Lab — condição composta","scenario":"Acesso premium exige conta ativa E (plano Pro OU papel de administrador).","instruction":"Confira casos em que apenas uma parte da condição é verdadeira.","options":["contaAtiva || planoPro || admin","contaAtiva && (planoPro || admin)","contaAtiva && planoPro && admin","!contaAtiva && (planoPro || admin)"],"answer":1,"cases":[{"input":"ativa=true, pro=true, admin=false","expected":"libera"},{"input":"ativa=true, pro=false, admin=true","expected":"libera"},{"input":"ativa=false, pro=true, admin=false","expected":"não libera"},{"input":"ativa=true, pro=false, admin=false","expected":"não libera"}],"feedback":"Agrupamento correto. Conta ativa é obrigatória e existem duas alternativas de perfil.","feedback_incorrect":"Essa expressão falha em pelo menos um caso. Verifique o requisito obrigatório e o grupo de alternativas."},"module":"Decisões","editorial_version":"lc-content-standard-1.0","pedagogy":"regra-ramos-casos-validacao"}$json$::jsonb
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=4;
update nexora.lessons
set objective=$txt$Decidir quando uma regra realmente precisa de aninhamento, distinguindo dependência entre perguntas de simples condição composta e reduzindo estruturas profundas difíceis de testar.$txt$,
    estimated_minutes=32,
    content=$json$[{"type":"concept","title":"Aninhamento é uma decisão que só faz sentido dentro de outro caminho","body":"Às vezes a segunda pergunta só deve existir depois que a primeira foi respondida. Por exemplo: primeiro verificar se existe saldo; somente se houver saldo suficiente, perguntar se o limite diário permite a operação.\n\nIsso é diferente de simplesmente colocar muitos IFs um dentro do outro."},{"type":"example","title":"Saque em duas etapas","body":"1. Se o saldo é insuficiente → recusar por saldo.\n2. Senão, verificar o limite diário.\n3. Se excede o limite → recusar por limite.\n4. Caso contrário → aprovar.\n\nA segunda regra depende do primeiro contexto: não faz sentido discutir limite diário quando o saldo já inviabiliza a operação."},{"type":"comparison","title":"Aninhamento × condição composta","items":["Use condição composta quando todas as perguntas pertencem ao mesmo nível lógico e você só precisa de verdadeiro/falso.","Use aninhamento quando o resultado da primeira decisão muda quais perguntas seguintes são relevantes.","Prefira guard clauses/saídas antecipadas quando elas reduzem profundidade sem alterar a regra.","Mais níveis não significam mais precisão."]},{"type":"guided_analysis","title":"Desenhe a árvore antes de escrever IFs","body":"Para cada nó, escreva uma pergunta. Para cada resposta, indique o próximo nó ou uma saída final. Se dois caminhos levam à mesma pergunta, talvez exista oportunidade de reorganizar a árvore.\n\nO desenho revela ramos impossíveis ou duplicados antes do código."},{"type":"mistake","title":"A pirâmide de IFs aumenta a carga de raciocínio","body":"Cinco níveis de aninhamento obrigam o leitor a lembrar todas as condições externas para entender a linha atual. Muitas vezes validações iniciais podem encerrar casos inválidos cedo e deixar o caminho principal mais linear."},{"type":"professional_context","title":"Fluxos de aprovação e validação usam árvores de decisão","body":"Crédito, cadastro, autenticação e triagem podem depender de etapas sucessivas. Representar a árvore e seus motivos de recusa ajuda operações, suporte e auditoria a entender por que cada caso terminou em determinado resultado."},{"type":"recap","items":["Aninhamento faz sentido quando perguntas dependem de contexto anterior.","Condição composta e aninhamento não são sinônimos.","Árvore de decisão ajuda a visualizar cobertura.","Profundidade excessiva é sinal de refatoração."]}]$json$::jsonb,
    lab_type='decision_table',
    lab_config=$json${"checkpoint":{"question":"Quando aninhamento é mais justificável?","options":["Quando queremos deixar qualquer código mais longo.","Quando uma segunda pergunta só é relevante após o resultado da primeira.","Sempre que existem dois booleanos.","Nunca; aninhamento é sempre errado."],"answer":1,"feedback":"Correto. A dependência entre perguntas é o motivo legítimo para aninhar.","feedback_incorrect":"Procure o cenário em que o contexto da primeira resposta determina se a próxima pergunta faz sentido."},"decision_table":{"title":"Decision Table — saque em etapas","scenario":"Regra: sem saldo suficiente → Recusar por saldo. Com saldo suficiente, se ultrapassar limite diário → Recusar por limite. Caso contrário → Aprovar.","outcomes":["Aprovar","Recusar: saldo","Recusar: limite"],"rows":[{"case":"saldo=100, saque=150, limite disponível=500","answer":1},{"case":"saldo=1000, saque=600, limite disponível=500","answer":2},{"case":"saldo=1000, saque=300, limite disponível=500","answer":0},{"case":"saldo=300, saque=300, limite disponível=300","answer":0}],"feedback":"Árvore consistente. Cada motivo de recusa aparece somente quando sua pergunta é relevante.","feedback_incorrect":"Revise a ordem: saldo é avaliado antes do limite diário."},"module":"Decisões","editorial_version":"lc-content-standard-1.0","pedagogy":"regra-ramos-casos-validacao"}$json$::jsonb
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=5;
update nexora.lessons
set objective=$txt$Usar tabela-verdade e matrizes de casos para verificar condições compostas, identificando combinações que uma leitura informal da expressão poderia esquecer.$txt$,
    estimated_minutes=30,
    content=$json$[{"type":"purpose","title":"Uma condição lógica é mais fácil de provar quando todas as combinações estão visíveis","body":"Com dois booleanos existem quatro combinações possíveis. Em vez de confiar apenas na intuição, uma tabela-verdade permite verificar cada uma e comparar o resultado com o requisito."},{"type":"concept","title":"Tabela-verdade é uma matriz de entradas e saída esperada","body":"Para A E B, apenas verdadeiro+verdadeiro produz verdadeiro. Para A OU B, qualquer combinação com pelo menos um verdadeiro produz verdadeiro.\n\nA tabela não é apenas teoria: é um roteiro de testes."},{"type":"example","title":"Acesso exige cadastro ativo E e-mail verificado","body":"ativo=true, verificado=true → libera.\nativo=true, verificado=false → bloqueia.\nativo=false, verificado=true → bloqueia.\nativo=false, verificado=false → bloqueia.\n\nAs quatro linhas provam o comportamento do operador E."},{"type":"mechanics","title":"Da tabela para os testes","items":["Liste todas as combinações relevantes.","Registre a saída esperada antes de executar.","Associe cada linha a um teste automatizado ou manual.","Quando houver três ou mais booleanos, priorize combinações de risco e limites, mas preserve cobertura lógica planejada."]},{"type":"guided_practice","title":"Construa a tabela antes de olhar a implementação","body":"Para uma regra `temDocumento && (maiorDeIdade || autorizado)`, escreva casos que isolem documento, idade e autorização. Só depois compare com a expressão. Essa ordem reduz o risco de adaptar a expectativa ao código existente."},{"type":"professional_context","title":"Tabela de decisão também documenta a regra para áreas não técnicas","body":"Uma matriz com entradas e resultados pode ser revisada por produto, operação e jurídico sem exigir leitura de código. Isso transforma regra de negócio em artefato verificável."},{"type":"recap","items":["Tabela-verdade expõe combinações possíveis.","Cada linha pode virar um teste.","A expectativa deve ser definida a partir da regra, não da implementação.","Matrizes de decisão facilitam revisão entre áreas."]}]$json$::jsonb,
    lab_type='decision_table',
    lab_config=$json${"checkpoint":{"question":"Para uma regra A E B, quando o resultado é verdadeiro?","options":["Quando apenas A é verdadeiro.","Quando apenas B é verdadeiro.","Quando A e B são verdadeiros.","Quando ambos são falsos."],"answer":2,"feedback":"Correto. O operador E exige as duas condições verdadeiras.","feedback_incorrect":"Revise a tabela-verdade do operador E."},"decision_table":{"title":"Decision Table — acesso verificado","scenario":"Acesso exige conta ativa E e-mail verificado.","outcomes":["Liberar","Bloquear"],"rows":[{"case":"ativa=true, verificado=true","answer":0},{"case":"ativa=true, verificado=false","answer":1},{"case":"ativa=false, verificado=true","answer":1},{"case":"ativa=false, verificado=false","answer":1}],"feedback":"Tabela correta. Você cobriu todas as combinações dos dois booleanos.","feedback_incorrect":"Com E, somente o caso em que as duas condições são verdadeiras libera."},"module":"Decisões","editorial_version":"lc-content-standard-1.0","pedagogy":"regra-ramos-casos-validacao"}$json$::jsonb
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=6;
update nexora.lessons
set objective=$txt$Projetar decisões robustas que tratem explicitamente dados ausentes, inválidos e estados inesperados antes de aplicar regras de negócio, distinguindo falha de entrada de resultado legítimo da regra.$txt$,
    estimated_minutes=38,
    content=$json$[{"type":"story","title":"Falso não é a mesma coisa que dado inválido","body":"Se uma idade chegou vazia, concluir simplesmente `idade >= 18 = falso` mistura duas situações diferentes: uma pessoa menor de idade e uma entrada que nem sequer contém idade válida.\n\nDecisões robustas tratam qualidade do dado antes de classificar o caso."},{"type":"concept","title":"Validação deve preceder a regra que depende do dado","body":"Antes de perguntar se `idade >= 18`, o sistema precisa saber se idade existe, é numérica e pertence a um intervalo plausível. Só depois uma comparação de negócio possui significado.\n\nEssa ordem evita que erro de entrada seja registrado como decisão legítima."},{"type":"comparison","title":"Três classes que não devem ser confundidas","items":["Caso válido que satisfaz a regra.","Caso válido que não satisfaz a regra.","Caso inválido/ausente que precisa de correção ou tratamento específico."]},{"type":"example","title":"Cadastro por idade","body":"idade=21 → válido e aprovado.\nidade=16 → válido e recusado pela regra de maioridade.\nidade ausente → não classificar como menor; solicitar dado.\nidade=-4 → inválido; corrigir entrada.\nidade=\"vinte\" → inválido para comparação numérica."},{"type":"guided_analysis","title":"Use guard clauses para limpar o caminho principal","body":"Uma estratégia é encerrar primeiro os casos inválidos: se idade ausente → pedir idade; se não numérica → erro de formato; se fora do intervalo → erro de domínio. Depois, com dado confiável, avaliar a regra de maioridade.\n\nIsso reduz aninhamento e separa validação de classificação."},{"type":"professional_context","title":"Motivos distintos melhoram suporte e analytics","body":"Se todo caso termina apenas em “recusado”, você perde informação sobre por que falhou. Estados como `dados_incompletos`, `formato_invalido` e `nao_elegivel` ajudam atendimento, métricas e correções do produto."},{"type":"mistake","title":"Fallback genérico pode esconder novos estados","body":"Um SENÃO final é útil quando o domínio está completamente conhecido. Se novas categorias ou estados podem aparecer, um fallback genérico pode mascarar ausência de tratamento. Registre ou sinalize estados inesperados."},{"type":"mastery","title":"Decisão robusta é aquela que explica o resultado","items":["Valida pré-condições.","Separa erro de entrada de regra de negócio.","Possui saída para cada classe relevante.","Registra motivo de recusa ou revisão.","Tem casos de teste normais, limites, ausentes e inválidos."]},{"type":"recap","items":["Ausente e inválido não são simplesmente falso.","Validação vem antes da classificação.","Guard clauses podem reduzir aninhamento.","Motivos explícitos tornam regras mais auditáveis."]}]$json$::jsonb,
    lab_type='decision_table',
    lab_config=$json${"checkpoint":{"question":"Se a idade obrigatória está ausente, qual é a abordagem mais robusta antes de avaliar `idade >= 18`?","options":["Tratar automaticamente como menor de idade.","Validar a ausência e solicitar/corrigir o dado antes da regra.","Converter ausência para 0 sem registrar.","Aprovar por padrão."],"answer":1,"feedback":"Correto. A regra de negócio só deve operar sobre dado válido.","feedback_incorrect":"Ausência de dado não é um resultado legítimo da comparação de maioridade."},"decision_table":{"title":"Decision Table — entradas robustas","scenario":"Cadastro exige idade válida. Idade >=18 aprova; idade válida abaixo de 18 recusa; dado ausente ou inválido deve ir para revisão de dados.","outcomes":["Aprovar","Recusar: menor","Revisar dados"],"rows":[{"case":"idade = 21","answer":0},{"case":"idade = 17","answer":1},{"case":"idade ausente","answer":2},{"case":"idade = -4","answer":2},{"case":"idade = \"vinte\"","answer":2}],"feedback":"Tratamento robusto. Você separou elegibilidade de qualidade do dado.","feedback_incorrect":"Não transforme entrada ausente ou inválida em uma recusa legítima por idade."},"module":"Decisões","editorial_version":"lc-content-standard-1.0","pedagogy":"regra-ramos-casos-validacao"}$json$::jsonb
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=7;
update nexora.questions
set prompt=$txt$Uma condição deve ser entendida principalmente como:$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"A ação que o sistema executa."},{"id":"b","label":"Uma pergunta que produz verdadeiro ou falso."},{"id":"c","label":"Um texto de erro."},{"id":"d","label":"Um laço de repetição."}]$json$::jsonb,correct_answer=$json${"option_id":"b"}$json$::jsonb,
    feedback_correct=$txt$Correto. A condição é a pergunta que orienta o caminho.$txt$,feedback_incorrect=$txt$Separe a pergunta da ação que será executada depois.$txt$,difficulty=1
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=1;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Uma condição deve ser entendida principalmente como:$txt$,'multiple_choice',$json$[{"id":"a","label":"A ação que o sistema executa."},{"id":"b","label":"Uma pergunta que produz verdadeiro ou falso."},{"id":"c","label":"Um texto de erro."},{"id":"d","label":"Um laço de repetição."}]$json$::jsonb,$json${"option_id":"b"}$json$::jsonb,$txt$Correto. A condição é a pergunta que orienta o caminho.$txt$,$txt$Separe a pergunta da ação que será executada depois.$txt$,1,1
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=1);
update nexora.questions
set prompt=$txt$Quando SE e SENÃO representam caminhos complementares, o que deve acontecer para uma entrada válida?$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"Os dois ramos executam."},{"id":"b","label":"Exatamente um ramo executa."},{"id":"c","label":"Nenhum ramo pode executar."},{"id":"d","label":"O SENÃO executa primeiro."}]$json$::jsonb,correct_answer=$json${"option_id":"b"}$json$::jsonb,
    feedback_correct=$txt$Correto. Uma bifurcação complementar leva a um único caminho.$txt$,feedback_incorrect=$txt$Os ramos representam respostas opostas à mesma condição.$txt$,difficulty=1
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=2;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Quando SE e SENÃO representam caminhos complementares, o que deve acontecer para uma entrada válida?$txt$,'multiple_choice',$json$[{"id":"a","label":"Os dois ramos executam."},{"id":"b","label":"Exatamente um ramo executa."},{"id":"c","label":"Nenhum ramo pode executar."},{"id":"d","label":"O SENÃO executa primeiro."}]$json$::jsonb,$json${"option_id":"b"}$json$::jsonb,$txt$Correto. Uma bifurcação complementar leva a um único caminho.$txt$,$txt$Os ramos representam respostas opostas à mesma condição.$txt$,1,2
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=2);
update nexora.questions
set prompt=$txt$Em uma cadeia: Aprovado >=7, Recuperação >=5, qual condição deve ser testada primeiro?$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"nota >= 5"},{"id":"b","label":"nota >= 7"},{"id":"c","label":"nota == 0"},{"id":"d","label":"A ordem é irrelevante."}]$json$::jsonb,correct_answer=$json${"option_id":"b"}$json$::jsonb,
    feedback_correct=$txt$Correto. Testar a faixa mais alta primeiro evita que ela seja capturada pela condição mais ampla.$txt$,feedback_incorrect=$txt$A primeira condição verdadeira encerra a cadeia.$txt$,difficulty=2
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=3;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Em uma cadeia: Aprovado >=7, Recuperação >=5, qual condição deve ser testada primeiro?$txt$,'multiple_choice',$json$[{"id":"a","label":"nota >= 5"},{"id":"b","label":"nota >= 7"},{"id":"c","label":"nota == 0"},{"id":"d","label":"A ordem é irrelevante."}]$json$::jsonb,$json${"option_id":"b"}$json$::jsonb,$txt$Correto. Testar a faixa mais alta primeiro evita que ela seja capturada pela condição mais ampla.$txt$,$txt$A primeira condição verdadeira encerra a cadeia.$txt$,2,3
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=3);
update nexora.questions
set prompt=$txt$Regra: conta ativa E (VIP OU compra alta). Qual expressão corresponde à regra?$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"ativa || vip || compraAlta"},{"id":"b","label":"ativa && (vip || compraAlta)"},{"id":"c","label":"ativa && vip && compraAlta"},{"id":"d","label":"!ativa && (vip || compraAlta)"}]$json$::jsonb,correct_answer=$json${"option_id":"b"}$json$::jsonb,
    feedback_correct=$txt$Correto. Ativa é obrigatória; VIP e compra alta são alternativas.$txt$,feedback_incorrect=$txt$Separe a exigência obrigatória do grupo de alternativas.$txt$,difficulty=2
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=4;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Regra: conta ativa E (VIP OU compra alta). Qual expressão corresponde à regra?$txt$,'multiple_choice',$json$[{"id":"a","label":"ativa || vip || compraAlta"},{"id":"b","label":"ativa && (vip || compraAlta)"},{"id":"c","label":"ativa && vip && compraAlta"},{"id":"d","label":"!ativa && (vip || compraAlta)"}]$json$::jsonb,$json${"option_id":"b"}$json$::jsonb,$txt$Correto. Ativa é obrigatória; VIP e compra alta são alternativas.$txt$,$txt$Separe a exigência obrigatória do grupo de alternativas.$txt$,2,4
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=4);
update nexora.questions
set prompt=$txt$Quando aninhamento é mais justificável?$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"Quando uma segunda pergunta só faz sentido após a primeira resposta."},{"id":"b","label":"Sempre que existem duas condições."},{"id":"c","label":"Para deixar o código mais longo."},{"id":"d","label":"Nunca."}]$json$::jsonb,correct_answer=$json${"option_id":"a"}$json$::jsonb,
    feedback_correct=$txt$Correto. Dependência contextual é o motivo legítimo para aninhar.$txt$,feedback_incorrect=$txt$Procure o cenário em que a primeira decisão determina se a segunda pergunta é relevante.$txt$,difficulty=2
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=5;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Quando aninhamento é mais justificável?$txt$,'multiple_choice',$json$[{"id":"a","label":"Quando uma segunda pergunta só faz sentido após a primeira resposta."},{"id":"b","label":"Sempre que existem duas condições."},{"id":"c","label":"Para deixar o código mais longo."},{"id":"d","label":"Nunca."}]$json$::jsonb,$json${"option_id":"a"}$json$::jsonb,$txt$Correto. Dependência contextual é o motivo legítimo para aninhar.$txt$,$txt$Procure o cenário em que a primeira decisão determina se a segunda pergunta é relevante.$txt$,2,5
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=5);
update nexora.questions
set prompt=$txt$Para a regra A E B, qual combinação deve produzir verdadeiro?$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"A=true, B=false"},{"id":"b","label":"A=false, B=true"},{"id":"c","label":"A=true, B=true"},{"id":"d","label":"A=false, B=false"}]$json$::jsonb,correct_answer=$json${"option_id":"c"}$json$::jsonb,
    feedback_correct=$txt$Correto. E exige ambas verdadeiras.$txt$,feedback_incorrect=$txt$Use a tabela-verdade do operador E.$txt$,difficulty=2
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=6;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Para a regra A E B, qual combinação deve produzir verdadeiro?$txt$,'multiple_choice',$json$[{"id":"a","label":"A=true, B=false"},{"id":"b","label":"A=false, B=true"},{"id":"c","label":"A=true, B=true"},{"id":"d","label":"A=false, B=false"}]$json$::jsonb,$json${"option_id":"c"}$json$::jsonb,$txt$Correto. E exige ambas verdadeiras.$txt$,$txt$Use a tabela-verdade do operador E.$txt$,2,6
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=6);
update nexora.questions
set prompt=$txt$Se uma idade obrigatória está ausente, antes de verificar maioridade o sistema deve:$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"Assumir idade 0."},{"id":"b","label":"Validar/sinalizar a ausência."},{"id":"c","label":"Aprovar por padrão."},{"id":"d","label":"Tratar como menor sem registrar motivo."}]$json$::jsonb,correct_answer=$json${"option_id":"b"}$json$::jsonb,
    feedback_correct=$txt$Correto. Qualidade do dado precisa ser tratada antes da regra de elegibilidade.$txt$,feedback_incorrect=$txt$Ausência não é um resultado legítimo da regra de maioridade.$txt$,difficulty=3
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=7;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Se uma idade obrigatória está ausente, antes de verificar maioridade o sistema deve:$txt$,'multiple_choice',$json$[{"id":"a","label":"Assumir idade 0."},{"id":"b","label":"Validar/sinalizar a ausência."},{"id":"c","label":"Aprovar por padrão."},{"id":"d","label":"Tratar como menor sem registrar motivo."}]$json$::jsonb,$json${"option_id":"b"}$json$::jsonb,$txt$Correto. Qualidade do dado precisa ser tratada antes da regra de elegibilidade.$txt$,$txt$Ausência não é um resultado legítimo da regra de maioridade.$txt$,3,7
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=7);
update nexora.questions
set prompt=$txt$Qual teste melhor revela problema de fronteira numa regra '7 ou mais = aprovado'?$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"nota=9"},{"id":"b","label":"nota=10"},{"id":"c","label":"nota=7"},{"id":"d","label":"nota=8"}]$json$::jsonb,correct_answer=$json${"option_id":"c"}$json$::jsonb,
    feedback_correct=$txt$Correto. O próprio limite distingue >= de >.$txt$,feedback_incorrect=$txt$Teste exatamente onde o resultado da regra muda.$txt$,difficulty=2
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=8;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Qual teste melhor revela problema de fronteira numa regra '7 ou mais = aprovado'?$txt$,'multiple_choice',$json$[{"id":"a","label":"nota=9"},{"id":"b","label":"nota=10"},{"id":"c","label":"nota=7"},{"id":"d","label":"nota=8"}]$json$::jsonb,$json${"option_id":"c"}$json$::jsonb,$txt$Correto. O próprio limite distingue >= de >.$txt$,$txt$Teste exatamente onde o resultado da regra muda.$txt$,2,8
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=8);
update nexora.questions
set prompt=$txt$Por que uma tabela de decisão é útil além do código?$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"Porque elimina a necessidade de testes."},{"id":"b","label":"Porque documenta entradas e resultados de forma revisável por diferentes áreas."},{"id":"c","label":"Porque sempre reduz a regra a um único IF."},{"id":"d","label":"Porque substitui validação."}]$json$::jsonb,correct_answer=$json${"option_id":"b"}$json$::jsonb,
    feedback_correct=$txt$Correto. A matriz torna a regra verificável sem depender da leitura da implementação.$txt$,feedback_incorrect=$txt$Pense em um artefato que permita comparar casos e saídas esperadas.$txt$,difficulty=3
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=9;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Por que uma tabela de decisão é útil além do código?$txt$,'multiple_choice',$json$[{"id":"a","label":"Porque elimina a necessidade de testes."},{"id":"b","label":"Porque documenta entradas e resultados de forma revisável por diferentes áreas."},{"id":"c","label":"Porque sempre reduz a regra a um único IF."},{"id":"d","label":"Porque substitui validação."}]$json$::jsonb,$json${"option_id":"b"}$json$::jsonb,$txt$Correto. A matriz torna a regra verificável sem depender da leitura da implementação.$txt$,$txt$Pense em um artefato que permita comparar casos e saídas esperadas.$txt$,3,9
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=9);
update nexora.questions
set prompt=$txt$Uma decisão robusta deve diferenciar:$txt$,question_type='multiple_choice',options=$json$[{"id":"a","label":"Somente verdadeiro e falso em qualquer situação."},{"id":"b","label":"Casos válidos aprovados/recusados e entradas inválidas ou ausentes."},{"id":"c","label":"Apenas casos aprovados."},{"id":"d","label":"Apenas erros técnicos."}]$json$::jsonb,correct_answer=$json${"option_id":"b"}$json$::jsonb,
    feedback_correct=$txt$Correto. Resultado da regra e qualidade da entrada são dimensões distintas.$txt$,feedback_incorrect=$txt$Dado inválido não deve ser confundido com caso válido que não satisfaz a regra.$txt$,difficulty=3
where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=10;
insert into nexora.questions(id,assessment_id,prompt,question_type,options,correct_answer,feedback_correct,feedback_incorrect,difficulty,position)
select gen_random_uuid(),(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1),$txt$Uma decisão robusta deve diferenciar:$txt$,'multiple_choice',$json$[{"id":"a","label":"Somente verdadeiro e falso em qualquer situação."},{"id":"b","label":"Casos válidos aprovados/recusados e entradas inválidas ou ausentes."},{"id":"c","label":"Apenas casos aprovados."},{"id":"d","label":"Apenas erros técnicos."}]$json$::jsonb,$json${"option_id":"b"}$json$::jsonb,$txt$Correto. Resultado da regra e qualidade da entrada são dimensões distintas.$txt$,$txt$Dado inválido não deve ser confundido com caso válido que não satisfaz a regra.$txt$,3,10
where not exists(select 1 from nexora.questions where assessment_id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1) and position=10);
update nexora.assessments
set title='Checkpoint aplicado — Decisões e cobertura de casos',pass_score=70,max_attempts=3
where id=(select a.id from nexora.assessments a where a.module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) order by a.created_at asc limit 1);
update nexora.learning_resources
set title=$txt$Apostila LC — Decisões e caminhos$txt$,resource_type='guide',summary=$txt$Síntese aplicada de condições, SE/SENÃO, faixas, lógica composta, aninhamento e tratamento de entradas inválidas.$txt$,content=$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Pergunta antes da ação","body":"Toda decisão começa por uma condição verificável. Separe a pergunta do efeito para conseguir testar a regra."},{"title":"Dois caminhos","body":"SE/SENÃO representa uma bifurcação. Quando os ramos são complementares, uma entrada válida deve cair em exatamente um deles."},{"title":"Várias faixas","body":"Em SENÃO SE, a primeira condição verdadeira vence. Converta a cadeia em intervalos e teste fronteiras."},{"title":"Condições compostas","body":"Use E, OU e NÃO de acordo com a semântica do requisito e explicite agrupamentos."},{"title":"Árvore e aninhamento","body":"Aninhe quando a pergunta seguinte depende do contexto da primeira. Reduza profundidade quando validações iniciais puderem encerrar casos."},{"title":"Robustez","body":"Trate ausente e inválido antes de aplicar regra de negócio. Registre motivos diferentes para resultados diferentes."}]}$json$::jsonb,status='published'
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=1;
insert into nexora.learning_resources(id,course_id,module_id,title,resource_type,summary,content,position,status)
select gen_random_uuid(),m.course_id,m.id,$txt$Apostila LC — Decisões e caminhos$txt$,'guide',$txt$Síntese aplicada de condições, SE/SENÃO, faixas, lógica composta, aninhamento e tratamento de entradas inválidas.$txt$,$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Pergunta antes da ação","body":"Toda decisão começa por uma condição verificável. Separe a pergunta do efeito para conseguir testar a regra."},{"title":"Dois caminhos","body":"SE/SENÃO representa uma bifurcação. Quando os ramos são complementares, uma entrada válida deve cair em exatamente um deles."},{"title":"Várias faixas","body":"Em SENÃO SE, a primeira condição verdadeira vence. Converta a cadeia em intervalos e teste fronteiras."},{"title":"Condições compostas","body":"Use E, OU e NÃO de acordo com a semântica do requisito e explicite agrupamentos."},{"title":"Árvore e aninhamento","body":"Aninhe quando a pergunta seguinte depende do contexto da primeira. Reduza profundidade quando validações iniciais puderem encerrar casos."},{"title":"Robustez","body":"Trate ausente e inválido antes de aplicar regra de negócio. Registre motivos diferentes para resultados diferentes."}]}$json$::jsonb,1,'published'
from nexora.modules m
where m.id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1)
  and not exists(select 1 from nexora.learning_resources r where r.module_id=m.id and r.position=1);
update nexora.learning_resources
set title=$txt$Checklist de cobertura de decisões$txt$,resource_type='checklist',summary=$txt$Roteiro para revisar ramos, fronteiras, faixas e casos inválidos antes de considerar uma regra pronta.$txt$,content=$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Cobertura","items":["Existe caso verdadeiro e falso?","Cada ramo foi exercitado?","As fronteiras foram testadas?","Faixas deixam lacunas ou se sobrepõem?","Existe tratamento de dado ausente/inválido?"]},{"title":"Legibilidade","items":["A condição pode ser explicada como frase?","Agrupamentos estão explícitos?","Motivos de recusa são distintos?","Aninhamento é realmente necessário?"]},{"title":"Evidência","body":"Para cada linha da regra, associe um caso de teste que demonstraria um erro se aquela parte estivesse incorreta."}]}$json$::jsonb,status='published'
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=2;
insert into nexora.learning_resources(id,course_id,module_id,title,resource_type,summary,content,position,status)
select gen_random_uuid(),m.course_id,m.id,$txt$Checklist de cobertura de decisões$txt$,'checklist',$txt$Roteiro para revisar ramos, fronteiras, faixas e casos inválidos antes de considerar uma regra pronta.$txt$,$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Cobertura","items":["Existe caso verdadeiro e falso?","Cada ramo foi exercitado?","As fronteiras foram testadas?","Faixas deixam lacunas ou se sobrepõem?","Existe tratamento de dado ausente/inválido?"]},{"title":"Legibilidade","items":["A condição pode ser explicada como frase?","Agrupamentos estão explícitos?","Motivos de recusa são distintos?","Aninhamento é realmente necessário?"]},{"title":"Evidência","body":"Para cada linha da regra, associe um caso de teste que demonstraria um erro se aquela parte estivesse incorreta."}]}$json$::jsonb,2,'published'
from nexora.modules m
where m.id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1)
  and not exists(select 1 from nexora.learning_resources r where r.module_id=m.id and r.position=2);
update nexora.learning_resources
set title=$txt$Oficina — Motor de classificação$txt$,resource_type='exercise',summary=$txt$Construa uma decisão multifaixa com tabela de casos, fronteiras e estados inválidos.$txt$,content=$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Cenário","body":"Classifique atendimento por prioridade: urgente, prioritário e normal, considerando nível informado e dado ausente."},{"title":"Entregável","items":["Defina condições em ordem.","Desenhe os ramos.","Crie uma tabela com pelo menos seis casos.","Inclua todas as fronteiras.","Inclua entrada ausente e inválida.","Registre motivo de cada saída."]},{"title":"Critério","body":"Outra pessoa deve conseguir alterar uma fronteira e identificar quais casos de teste precisam mudar."}]}$json$::jsonb,status='published'
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=3;
insert into nexora.learning_resources(id,course_id,module_id,title,resource_type,summary,content,position,status)
select gen_random_uuid(),m.course_id,m.id,$txt$Oficina — Motor de classificação$txt$,'exercise',$txt$Construa uma decisão multifaixa com tabela de casos, fronteiras e estados inválidos.$txt$,$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Cenário","body":"Classifique atendimento por prioridade: urgente, prioritário e normal, considerando nível informado e dado ausente."},{"title":"Entregável","items":["Defina condições em ordem.","Desenhe os ramos.","Crie uma tabela com pelo menos seis casos.","Inclua todas as fronteiras.","Inclua entrada ausente e inválida.","Registre motivo de cada saída."]},{"title":"Critério","body":"Outra pessoa deve conseguir alterar uma fronteira e identificar quais casos de teste precisam mudar."}]}$json$::jsonb,3,'published'
from nexora.modules m
where m.id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1)
  and not exists(select 1 from nexora.learning_resources r where r.module_id=m.id and r.position=3);
update nexora.learning_resources
set title=$txt$Caderno de bugs — Decisões$txt$,resource_type='exercise',summary=$txt$Casos curtos para localizar condição invertida, faixa inalcançável, OU permissivo, aninhamento excessivo e fallback que mascara dados inválidos.$txt$,content=$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Bug 1 — Fronteira","body":"Regra diz '18 ou mais', implementação usa >18. Identifique o menor caso que prova o erro."},{"title":"Bug 2 — Faixa inalcançável","body":"A cadeia testa nota>=5 antes de nota>=7. Explique por que o segundo ramo fica parcialmente inacessível."},{"title":"Bug 3 — OU permissivo","body":"Acesso exige ativo E admin, implementação usa OU. Monte dois casos de acesso indevido."},{"title":"Bug 4 — Pirâmide","body":"Cinco validações estão aninhadas. Reescreva conceitualmente com guard clauses."},{"title":"Bug 5 — Dado ausente","body":"Campo vazio é convertido para 0 e classificado como não elegível. Separe erro de entrada de resultado da regra."}]}$json$::jsonb,status='published'
where module_id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1) and position=4;
insert into nexora.learning_resources(id,course_id,module_id,title,resource_type,summary,content,position,status)
select gen_random_uuid(),m.course_id,m.id,$txt$Caderno de bugs — Decisões$txt$,'exercise',$txt$Casos curtos para localizar condição invertida, faixa inalcançável, OU permissivo, aninhamento excessivo e fallback que mascara dados inválidos.$txt$,$json${"editorial_version":"lc-content-standard-1.0","sections":[{"title":"Bug 1 — Fronteira","body":"Regra diz '18 ou mais', implementação usa >18. Identifique o menor caso que prova o erro."},{"title":"Bug 2 — Faixa inalcançável","body":"A cadeia testa nota>=5 antes de nota>=7. Explique por que o segundo ramo fica parcialmente inacessível."},{"title":"Bug 3 — OU permissivo","body":"Acesso exige ativo E admin, implementação usa OU. Monte dois casos de acesso indevido."},{"title":"Bug 4 — Pirâmide","body":"Cinco validações estão aninhadas. Reescreva conceitualmente com guard clauses."},{"title":"Bug 5 — Dado ausente","body":"Campo vazio é convertido para 0 e classificado como não elegível. Separe erro de entrada de resultado da regra."}]}$json$::jsonb,4,'published'
from nexora.modules m
where m.id=(select m.id from nexora.modules m join nexora.courses c on c.id=m.course_id where c.slug='logica-programacao-basica' and m.position=3 limit 1)
  and not exists(select 1 from nexora.learning_resources r where r.module_id=m.id and r.position=4);
commit;